src/Entity/User.php
<?php

namespace App\Entity;

use App\Data\EmailReceiver;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Uid\Ulid;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User implements UserInterface, EmailReceiver
{
    public const USERNAME_FORMAT = '[A-Za-z0-9_.-]+';

    public const ROLE_USER = 'ROLE_USER';
    public const ROLE_ADMIN = 'ROLE_ADMIN';

    public const DEFAULT_ROLES = [ self::ROLE_USER ];

    public const AVATAR_FALLBACK = '';

    /**
     * @ORM\Id()
     * @ORM\Column(type="string", length=26)
     */
    private string $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private string $email;

    /**
     * @ORM\Column(type="string", length=36)
     */
    private string $username;

    /**
     * @ORM\Column(type="string", length=2)
     */
    private string $locale;

    /**
     * @ORM\Column(type="json")
     */
    private array $roles = [];

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private \DateTimeInterface $createdAt;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private string $avatarSource;

    /**
     * @var ArrayCollection|Authenticator[]
     * @ORM\OneToMany(targetEntity="App\Entity\Authenticator", mappedBy="user", cascade={"remove"})
     */
    private $authenticators;

    /**
     * @var ArrayCollection|Notification[]
     * @ORM\OneToMany(targetEntity="App\Entity\Notification", mappedBy="user", orphanRemoval=true)
     * @ORM\OrderBy({"timestamp": "DESC"})
     */
    private $notifications;

    public function __construct(string $email, string $username, string $locale, array $roles = self::DEFAULT_ROLES)
    {
        $this->id = new Ulid();
        $this->email = $email;
        $this->username = $username;
        $this->locale = $locale;
        $this->roles = $roles;
        $this->createdAt = new \DateTimeImmutable();
        $this->avatarSource = self::AVATAR_FALLBACK;
        $this->authenticators = new ArrayCollection();
        $this->notifications = new ArrayCollection();
    }

    public function getId(): string
    {
        return $this->id;
    }

    public function getEmail(): string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getRoles(): ?array
    {
        return $this->roles;
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    public function isAdmin(): bool
    {
        return in_array(self::ROLE_ADMIN, $this->roles);
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function getAvatarSource(): ?string
    {
        return $this->avatarSource;
    }

    public function setAvatarSource(string $avatarSource): self
    {
        $this->avatarSource = $avatarSource;

        return $this;
    }

    public function getUsername(): string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getLocale(): string
    {
        return $this->locale;
    }

    public function setLocale(string $locale): self
    {
        $this->locale = $locale;

        return $this;
    }

    /**
     * @return Authenticator[]|Collection
     */
    public function getAuthenticators(string $type): Collection
    {
        return $this->authenticators->filter(function (Authenticator $auth) use ($type) {
            return $auth->getType() === $type && $auth->isValid();
        });
    }

    public function getAuthenticator(string $type): ?Authenticator
    {
        return $this->getAuthenticators($type)->first() ?: null;
    }

    public function getPassword()
    {
        return null;
    }

    public function getSalt()
    {
        return null;
    }

    public function eraseCredentials()
    {
    }

    /**
     * @return Collection|Notification[]
     */
    public function getNotifications(): Collection
    {
        return $this->notifications;
    }

    public function countUnreadNotifications(): int
    {
        return $this->notifications->filter(function (Notification $notification) {
            return !$notification->isRead();
        })->count();
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\EventSubscriber\LocaleSubscriber;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Annotation\Route;

final class HomeController extends AbstractController
{
    /**
     * @Route("/")
     */
    public function index(\Parsedown $parsedown)
    {
        return $this->render('home/index.html.twig', [
            'readme' => $parsedown->parse(file_get_contents($this->getParameter('kernel.project_dir') . '/README.md')),
        ])->setSharedMaxAge(24 * 60 * 60);
    }

    /**
     * @Route("/terms")
     */
    public function terms()
    {
        return $this->render('home/terms.html.twig');
    }

    /**
     * @Route("/locale/{locale}")
     */
    public function locale(string $locale, Request $request, SessionInterface $session, EntityManagerInterface $em)
    {
        $locales = $this->getParameter('locales');
        if (array_key_exists($locale, $locales)) {
            $session->set(LocaleSubscriber::LOCALE_SESSION_KEY, $locale);
            $user = $this->getUser();
            if ($user instanceof User) {
                $user->setLocale($locale);
                $em->persist($user);
                $em->flush();
            }
        }

        return $this->redirect($request->server->get('HTTP_REFERER') ?? $this->generateUrl('app_home_index'));
    }
}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block content %}
    <div class="container py-4">
        {{ readme|raw }}
    </div>
{% endblock %}

templates/home/terms.html.twig
{% extends 'base.html.twig' %}

{% block content %}
    <div class="container py-4">
        <div class="row">
            <div class="col-12 col-xl-8 offset-xl-2">
                <h2>
                    {{ icon('gavel') }}
                    {{ 'terms.header'|trans }}
                </h2>

                <p><em>{{ 'terms.lastUpdate'|trans }}</em></p>

                <p>{{ 'terms.intro'|trans({'%website%': app.request.host, '%operator%': 'main.author'|trans, '%email%': 'main.email'|trans})|raw }}</p>
                <p>{{ 'terms.agree'|trans }}</p>

                <h3>{{ 'terms.accounts.header'|trans }}</h3>
                <p>{{ 'terms.accounts.password'|trans }}</p>
                <p>{{ 'terms.accounts.terminate'|trans }}</p>

                <h3>{{ 'terms.content.header'|trans }}</h3>
                <p>{{ 'terms.content.license'|trans }}</p>
                <p>{{ 'terms.content.disclaimer'|trans }}</p>
                <p>{{ 'terms.content.forbidden'|trans }}</p>
                <p>{{ 'terms.content.responsibility'|trans }}</p>


                <h3>{{ 'terms.privacy.header'|trans }}</h3>
                <p>{{ 'terms.privacy.effort'|trans }}</p>
                <p>{{ 'terms.privacy.noPrivate'|trans }}</p>
                <p>{{ 'terms.privacy.cookies'|trans|raw }}</p>
                <p>{{ 'terms.privacy.edit'|trans }}</p>
                <p>{{ 'terms.privacy.analytics'|trans|raw }}</p>
                <p>{{ 'terms.privacy.embed'|trans|raw }}</p>
                <p>{{ 'terms.privacy.logsStorage'|trans }}</p>
                <p>{{ 'terms.privacy.gdpr'|trans }}</p>

                <h3>{{ 'terms.general.header'|trans }}</h3>
                <p>{{ 'terms.general.law'|trans }}</p>
                <p>{{ 'terms.general.modify'|trans }}</p>
            </div>
        </div>
    </div>
{% endblock %}